

server:
  port: 8080
  max-http-header-size: 102400

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springdemo.com.entity
  configuration:
    cache-enabled: true
logging:
  file:
    path: D:\IJProjects\SpringDemo\log
  level:
    com.example.springdemo.com.mapper: debug

person:
  username: "张三"
  password: "zhang"
  age: "15"